name: Push Starter Project Subdirectory to Another Repo
on:
  push:
    branches:
      - main
    # paths:
    #   - "apps/next-wordpress-starter/**"
permissions: write-all

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          # ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Push to another repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          repository: CalebBarnes/nextwp-starter
          directory: apps/next-wordpress-starter
          branch: main
          force: true
